### ISSUE TITLE
Turning lights

### ISSUE THREAD

**Issue by luking-dev** [luckyz/robot#1]
Add LEDs.
Allow turn ON/OFF the lights.
Blink every 1 second the corresponding LED when turning left or right.
Keep the previous state of the lights after turning to the side. If they were on, keep it up. Otherwise, turn them off.

**Comment by luckyz** [comment]
3e67e144baea70db3cd91982f366b94d98e5ad22

**Comment by luckyz** [comment]
3e67e144baea70db3cd91982f366b94d98e5ad22

**Comment by luckyz** [comment]
fixed 3e67e144baea70db3cd91982f366b94d98e5ad22

**Comment by luking-dev** [comment]
fixed 3e67e144baea70db3cd91982f366b94d98e5ad22
